### ISSUE TITLE
Document or otherwise enforce required audio directive properties

### ISSUE THREAD

**Issue by tjaffri** [cameronhunter/alexa-response#6]
This is minor, but I ran into these when building an actual audio enabled skill:
1. The URL of the media you are streaming has to be HTTPs otherwise Alexa will not accept it.
2. The token field is required, otherwise Alexa will fail silently.

Some suggestions:

1. Note these requirements in the README
2. Update the test here `https://github.com/cameronhunter/alexa-response/blob/master/test/directives-test.js` to use an HTTPS url for the test case, and specify a token
3. Throw an Error if somebody tries to use a non-HTTPS url or does not specify token, so that the unit test fails when testing locally (for those who are actually writing a local unit test, e.g. like you do in your starter). It was a little tricky to discover what the root cause was when it failed for me on AWS lambda so you'll be saving people some time.

Let me know what you think... happy to send a PR if you agree, but thought I would check with you first before I wrote code.

Probably not a high priority thing to do either way. I'll use your latest bits and let you know if there are any bugs I find.

**Comment by cameronhunter** [comment]
Hi @tjaffri, could you migrate this issue to the monorepo please?
